name: Deploy Workflow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
          npm install -g pnpm
      - name: Cache pnpm
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
      - name: Build
        run: |
          pnpm build
      - name: Deploy to OSS
        env:
          OSS_AccessKeyID: ${{ secrets.ACCESS_KEY_ID }}
          OSS_AccessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          OSS_EndPoint: oss-cn-hangzhou.aliyuncs.com
          OSS_Bucket: songhn-homepage
        run: |
          wget -q http://gosspublic.alicdn.com/ossutil/1.6.10/ossutil64
          chmod +x ./ossutil64
          ./ossutil64 config -e $OSS_EndPoint -i $OSS_AccessKeyID -k $OSS_AccessKeySecret -L CH
          ./ossutil64 rm -r -f oss://$OSS_Bucket/
          ./ossutil64 cp -r -f ./dist oss://$OSS_Bucket/